"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# 專案的所有設定都在這，包括資料庫、已安裝的 App、靜態檔案、時區等。

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 設定一個專案的「根目錄」，讓你之後引用檔案時不用寫死絕對路徑。
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY：網站加密用，很重要，正式版不能外洩。

SECRET_KEY = 'django-insecure-1dy@cp0c)nnue2)w@#8!iy_(_*gb+9gmq!=yptxw#ng7t8^!#c'

# SECURITY WARNING: don't run with debug turned on in production!

#DEBUG：開發時可以開，正式上線時要關。
DEBUG = True

# ALLOWED_HOSTS：允許哪些網域來連線，開發中可以空白。
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',# 讓你用 /admin 登入管理資料
    'django.contrib.auth',#用戶驗證系統
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'signingsystem',# 我的 App 名字 (自己加的)
    'corsheaders',#讓前後端可以互相請求 CORS 套件(自己加的)
    'social_django',#啟用了 social-auth-app-django 這個套件
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',#讓 API 支援跨來源存取（CORS）(自己加的)
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls' #告訴 Django：「網址對應表」在哪一個檔案。

#模板系統
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#WSGI 設定
WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#資料庫設定(預設用 SQLite，檔案型資料庫。未來也可以換成 MySQL、PostgreSQL 等。)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
#密碼驗證設定 (Password Validation)

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
#國際化設定

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
#靜態檔案設定 (Static files)

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
#主鍵預設型別

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = ["http://localhost:8000"]
CORS_ALLOW_CREDENTIALS = True

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',#讓 Django 支援 用 Google 登入
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '837507662650-9i6p7lgbqm2n4r1ofg5h8oluljqiu61p.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/post-login/'


LOGOUT_REDIRECT_URL = '/'